### ISSUE TITLE
编辑时php error

### ISSUE THREAD

**Issue by swaylq** [narutolhy/web-for-tongqu-test#1]
![image](https://cloud.githubusercontent.com/assets/5630262/6689767/47f8443a-ccf7-11e4-8ac6-2ab6c5e434d4.png)

**Comment by narutolhy** [comment]
唔，我这边都顺利通过了，请问还有其他地方有问题吗？这个函数是在view/logged_in_area.php中调用的，line 19-27行

**Comment by narutolhy** [comment]
打错，是我这边顺利通过了。

**Comment by narutolhy** [comment]
segments = array(
				'text',
				'change',
				'due_date' => $row->due_date,
				'todo_text'=> $todo_text,
				'id' => $row->todo_id
				);
			//echo anchor('text/change/'.$data,'修改');
            echo anchor(site_url($segment
