### ISSUE TITLE
编辑项目的 URL 设计

### ISSUE THREAD

**Issue by arrowrowe** [narutolhy/web-for-tongqu-test#2]
目前的 URL 是 due_date/todo_text/id, 建议只要求 id, 其余属性自行从数据库查.

@swaylq 提的 #1 原因也在这里, 当 todo_text 为空时 (这在创建项目时没有被禁止), URL 形如 due_date//id, 因而, CI 调用 controllers/text 的 change 函数时, 把 id 作为了 todo_text 而 id 为空, 出错.

**Comment by arrowrowe** [comment]
顺便提些细节:
- 登录页面的 img/login_bg.jpg 404 了.
- 直接用 ci 的 form_helper 时, 生成的 input 大多用了 value 而非 placeholder.
- 创建项目时未校验日期格式, strict mode 下报错, 非 strict mode 下生成不合法日期(如 0000-00-00).
- 数据库中表 todo_todos 的 text 字段未设置默认值, strict mode 下报错.
- 数据库中两张表的编码都是 latin1_swedish_ci.

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by narutolhy** [comment]
多谢指教。URL是因为我想向view/change里面传递todo_text和id，因为之前已经提取过，觉得在搜索一次数据库有点浪费时间。我对初始化设置默认值和格式问题还有些不熟悉，我会多多改进

**Comment by arrowrowe** [comment]
因时间太久而关闭.
